# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from serv import iandun_pb2 as serv_dot_iandun__pb2


class GreeterStub(object):
    """创建服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenderResults = channel.unary_unary(
                '/pyserver.Greeter/GenderResults',
                request_serializer=serv_dot_iandun__pb2.GenderRequest.SerializeToString,
                response_deserializer=serv_dot_iandun__pb2.GenderReply.FromString,
                )
        self.PhyResults = channel.unary_unary(
                '/pyserver.Greeter/PhyResults',
                request_serializer=serv_dot_iandun__pb2.PhyRequest.SerializeToString,
                response_deserializer=serv_dot_iandun__pb2.PhyReply.FromString,
                )
        self.PhySiologicalCycleStage = channel.unary_unary(
                '/pyserver.Greeter/PhySiologicalCycleStage',
                request_serializer=serv_dot_iandun__pb2.PhySiologicalCycleStageRequest.SerializeToString,
                response_deserializer=serv_dot_iandun__pb2.PhySiologicalCycleStageReply.FromString,
                )
        self.QuickResults = channel.unary_unary(
                '/pyserver.Greeter/QuickResults',
                request_serializer=serv_dot_iandun__pb2.QuickRequest.SerializeToString,
                response_deserializer=serv_dot_iandun__pb2.QuickReply.FromString,
                )
        self.PhySiologicalCyclePersonalModel = channel.unary_unary(
                '/pyserver.Greeter/PhySiologicalCyclePersonalModel',
                request_serializer=serv_dot_iandun__pb2.PhySiologicalCyclePersonalModelRequest.SerializeToString,
                response_deserializer=serv_dot_iandun__pb2.PhySiologicalCyclePersonalModelReply.FromString,
                )
        self.PhySiologicalCycleCommonModel = channel.unary_unary(
                '/pyserver.Greeter/PhySiologicalCycleCommonModel',
                request_serializer=serv_dot_iandun__pb2.PhySiologicalCycleCommonModelRequest.SerializeToString,
                response_deserializer=serv_dot_iandun__pb2.PhySiologicalCycleCommonModelReply.FromString,
                )


class GreeterServicer(object):
    """创建服务
    """

    def GenderResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PhyResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PhySiologicalCycleStage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuickResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PhySiologicalCyclePersonalModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PhySiologicalCycleCommonModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenderResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GenderResults,
                    request_deserializer=serv_dot_iandun__pb2.GenderRequest.FromString,
                    response_serializer=serv_dot_iandun__pb2.GenderReply.SerializeToString,
            ),
            'PhyResults': grpc.unary_unary_rpc_method_handler(
                    servicer.PhyResults,
                    request_deserializer=serv_dot_iandun__pb2.PhyRequest.FromString,
                    response_serializer=serv_dot_iandun__pb2.PhyReply.SerializeToString,
            ),
            'PhySiologicalCycleStage': grpc.unary_unary_rpc_method_handler(
                    servicer.PhySiologicalCycleStage,
                    request_deserializer=serv_dot_iandun__pb2.PhySiologicalCycleStageRequest.FromString,
                    response_serializer=serv_dot_iandun__pb2.PhySiologicalCycleStageReply.SerializeToString,
            ),
            'QuickResults': grpc.unary_unary_rpc_method_handler(
                    servicer.QuickResults,
                    request_deserializer=serv_dot_iandun__pb2.QuickRequest.FromString,
                    response_serializer=serv_dot_iandun__pb2.QuickReply.SerializeToString,
            ),
            'PhySiologicalCyclePersonalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.PhySiologicalCyclePersonalModel,
                    request_deserializer=serv_dot_iandun__pb2.PhySiologicalCyclePersonalModelRequest.FromString,
                    response_serializer=serv_dot_iandun__pb2.PhySiologicalCyclePersonalModelReply.SerializeToString,
            ),
            'PhySiologicalCycleCommonModel': grpc.unary_unary_rpc_method_handler(
                    servicer.PhySiologicalCycleCommonModel,
                    request_deserializer=serv_dot_iandun__pb2.PhySiologicalCycleCommonModelRequest.FromString,
                    response_serializer=serv_dot_iandun__pb2.PhySiologicalCycleCommonModelReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pyserver.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """创建服务
    """

    @staticmethod
    def GenderResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pyserver.Greeter/GenderResults',
            serv_dot_iandun__pb2.GenderRequest.SerializeToString,
            serv_dot_iandun__pb2.GenderReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PhyResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pyserver.Greeter/PhyResults',
            serv_dot_iandun__pb2.PhyRequest.SerializeToString,
            serv_dot_iandun__pb2.PhyReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PhySiologicalCycleStage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pyserver.Greeter/PhySiologicalCycleStage',
            serv_dot_iandun__pb2.PhySiologicalCycleStageRequest.SerializeToString,
            serv_dot_iandun__pb2.PhySiologicalCycleStageReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QuickResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pyserver.Greeter/QuickResults',
            serv_dot_iandun__pb2.QuickRequest.SerializeToString,
            serv_dot_iandun__pb2.QuickReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PhySiologicalCyclePersonalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pyserver.Greeter/PhySiologicalCyclePersonalModel',
            serv_dot_iandun__pb2.PhySiologicalCyclePersonalModelRequest.SerializeToString,
            serv_dot_iandun__pb2.PhySiologicalCyclePersonalModelReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PhySiologicalCycleCommonModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pyserver.Greeter/PhySiologicalCycleCommonModel',
            serv_dot_iandun__pb2.PhySiologicalCycleCommonModelRequest.SerializeToString,
            serv_dot_iandun__pb2.PhySiologicalCycleCommonModelReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
