# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serv/iandun.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='serv/iandun.proto',
  package='pyserver',
  syntax='proto3',
  serialized_options=b'\n\023org.jpdna.grpchelloB\rPyServerProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11serv/iandun.proto\x12\x08pyserver\"*\n\rGenderRequest\x12\x0b\n\x03ids\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\"f\n\nPhyRequest\x12\x0b\n\x03ids\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x18\n\x10men_start_latest\x18\x03 \x01(\t\x12\x10\n\x08men_keep\x18\x04 \x01(\t\x12\x11\n\tmen_cycle\x18\x05 \x01(\t\";\n\x1ePhySiologicalCycleStageRequest\x12\x0b\n\x03ids\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\"C\n$PhySiologicalCycleCommonModelRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0e\n\x06update\x18\x02 \x01(\t\"5\n\"PhySiologicalCycleCommonModelReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"E\n&PhySiologicalCyclePersonalModelRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0e\n\x06update\x18\x02 \x01(\t\"7\n$PhySiologicalCyclePersonalModelReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0bGenderReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x08PhyReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"/\n\x1cPhySiologicalCycleStageReply\x12\x0f\n\x07message\x18\x01 \x01(\t\")\n\x0cQuickRequest\x12\x0b\n\x03hrs\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\"\x1d\n\nQuickReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xbe\x04\n\x07Greeter\x12\x41\n\rGenderResults\x12\x17.pyserver.GenderRequest\x1a\x15.pyserver.GenderReply\"\x00\x12\x38\n\nPhyResults\x12\x14.pyserver.PhyRequest\x1a\x12.pyserver.PhyReply\"\x00\x12m\n\x17PhySiologicalCycleStage\x12(.pyserver.PhySiologicalCycleStageRequest\x1a&.pyserver.PhySiologicalCycleStageReply\"\x00\x12>\n\x0cQuickResults\x12\x16.pyserver.QuickRequest\x1a\x14.pyserver.QuickReply\"\x00\x12\x85\x01\n\x1fPhySiologicalCyclePersonalModel\x12\x30.pyserver.PhySiologicalCyclePersonalModelRequest\x1a..pyserver.PhySiologicalCyclePersonalModelReply\"\x00\x12\x7f\n\x1dPhySiologicalCycleCommonModel\x12..pyserver.PhySiologicalCycleCommonModelRequest\x1a,.pyserver.PhySiologicalCycleCommonModelReply\"\x00\x42&\n\x13org.jpdna.grpchelloB\rPyServerProtoP\x01\x62\x06proto3'
)




_GENDERREQUEST = _descriptor.Descriptor(
  name='GenderRequest',
  full_name='pyserver.GenderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='pyserver.GenderRequest.ids', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='pyserver.GenderRequest.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=73,
)


_PHYREQUEST = _descriptor.Descriptor(
  name='PhyRequest',
  full_name='pyserver.PhyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='pyserver.PhyRequest.ids', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='pyserver.PhyRequest.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='men_start_latest', full_name='pyserver.PhyRequest.men_start_latest', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='men_keep', full_name='pyserver.PhyRequest.men_keep', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='men_cycle', full_name='pyserver.PhyRequest.men_cycle', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=177,
)


_PHYSIOLOGICALCYCLESTAGEREQUEST = _descriptor.Descriptor(
  name='PhySiologicalCycleStageRequest',
  full_name='pyserver.PhySiologicalCycleStageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='pyserver.PhySiologicalCycleStageRequest.ids', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='pyserver.PhySiologicalCycleStageRequest.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=238,
)


_PHYSIOLOGICALCYCLECOMMONMODELREQUEST = _descriptor.Descriptor(
  name='PhySiologicalCycleCommonModelRequest',
  full_name='pyserver.PhySiologicalCycleCommonModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='pyserver.PhySiologicalCycleCommonModelRequest.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update', full_name='pyserver.PhySiologicalCycleCommonModelRequest.update', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=307,
)


_PHYSIOLOGICALCYCLECOMMONMODELREPLY = _descriptor.Descriptor(
  name='PhySiologicalCycleCommonModelReply',
  full_name='pyserver.PhySiologicalCycleCommonModelReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pyserver.PhySiologicalCycleCommonModelReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=362,
)


_PHYSIOLOGICALCYCLEPERSONALMODELREQUEST = _descriptor.Descriptor(
  name='PhySiologicalCyclePersonalModelRequest',
  full_name='pyserver.PhySiologicalCyclePersonalModelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='pyserver.PhySiologicalCyclePersonalModelRequest.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update', full_name='pyserver.PhySiologicalCyclePersonalModelRequest.update', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=433,
)


_PHYSIOLOGICALCYCLEPERSONALMODELREPLY = _descriptor.Descriptor(
  name='PhySiologicalCyclePersonalModelReply',
  full_name='pyserver.PhySiologicalCyclePersonalModelReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pyserver.PhySiologicalCyclePersonalModelReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=490,
)


_GENDERREPLY = _descriptor.Descriptor(
  name='GenderReply',
  full_name='pyserver.GenderReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pyserver.GenderReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=522,
)


_PHYREPLY = _descriptor.Descriptor(
  name='PhyReply',
  full_name='pyserver.PhyReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pyserver.PhyReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=551,
)


_PHYSIOLOGICALCYCLESTAGEREPLY = _descriptor.Descriptor(
  name='PhySiologicalCycleStageReply',
  full_name='pyserver.PhySiologicalCycleStageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pyserver.PhySiologicalCycleStageReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=600,
)


_QUICKREQUEST = _descriptor.Descriptor(
  name='QuickRequest',
  full_name='pyserver.QuickRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hrs', full_name='pyserver.QuickRequest.hrs', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='pyserver.QuickRequest.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=602,
  serialized_end=643,
)


_QUICKREPLY = _descriptor.Descriptor(
  name='QuickReply',
  full_name='pyserver.QuickReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pyserver.QuickReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=645,
  serialized_end=674,
)

DESCRIPTOR.message_types_by_name['GenderRequest'] = _GENDERREQUEST
DESCRIPTOR.message_types_by_name['PhyRequest'] = _PHYREQUEST
DESCRIPTOR.message_types_by_name['PhySiologicalCycleStageRequest'] = _PHYSIOLOGICALCYCLESTAGEREQUEST
DESCRIPTOR.message_types_by_name['PhySiologicalCycleCommonModelRequest'] = _PHYSIOLOGICALCYCLECOMMONMODELREQUEST
DESCRIPTOR.message_types_by_name['PhySiologicalCycleCommonModelReply'] = _PHYSIOLOGICALCYCLECOMMONMODELREPLY
DESCRIPTOR.message_types_by_name['PhySiologicalCyclePersonalModelRequest'] = _PHYSIOLOGICALCYCLEPERSONALMODELREQUEST
DESCRIPTOR.message_types_by_name['PhySiologicalCyclePersonalModelReply'] = _PHYSIOLOGICALCYCLEPERSONALMODELREPLY
DESCRIPTOR.message_types_by_name['GenderReply'] = _GENDERREPLY
DESCRIPTOR.message_types_by_name['PhyReply'] = _PHYREPLY
DESCRIPTOR.message_types_by_name['PhySiologicalCycleStageReply'] = _PHYSIOLOGICALCYCLESTAGEREPLY
DESCRIPTOR.message_types_by_name['QuickRequest'] = _QUICKREQUEST
DESCRIPTOR.message_types_by_name['QuickReply'] = _QUICKREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenderRequest = _reflection.GeneratedProtocolMessageType('GenderRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENDERREQUEST,
  '__module__' : 'serv.iandun_pb2'
  # @@protoc_insertion_point(class_scope:pyserver.GenderRequest)
  })
_sym_db.RegisterMessage(GenderRequest)

PhyRequest = _reflection.GeneratedProtocolMessageType('PhyRequest', (_message.Message,), {
  'DESCRIPTOR' : _PHYREQUEST,
  '__module__' : 'serv.iandun_pb2'
  # @@protoc_insertion_point(class_scope:pyserver.PhyRequest)
  })
_sym_db.RegisterMessage(PhyRequest)

PhySiologicalCycleStageRequest = _reflection.GeneratedProtocolMessageType('PhySiologicalCycleStageRequest', (_message.Message,), {
  'DESCRIPTOR' : _PHYSIOLOGICALCYCLESTAGEREQUEST,
  '__module__' : 'serv.iandun_pb2'
  # @@protoc_insertion_point(class_scope:pyserver.PhySiologicalCycleStageRequest)
  })
_sym_db.RegisterMessage(PhySiologicalCycleStageRequest)

PhySiologicalCycleCommonModelRequest = _reflection.GeneratedProtocolMessageType('PhySiologicalCycleCommonModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _PHYSIOLOGICALCYCLECOMMONMODELREQUEST,
  '__module__' : 'serv.iandun_pb2'
  # @@protoc_insertion_point(class_scope:pyserver.PhySiologicalCycleCommonModelRequest)
  })
_sym_db.RegisterMessage(PhySiologicalCycleCommonModelRequest)

PhySiologicalCycleCommonModelReply = _reflection.GeneratedProtocolMessageType('PhySiologicalCycleCommonModelReply', (_message.Message,), {
  'DESCRIPTOR' : _PHYSIOLOGICALCYCLECOMMONMODELREPLY,
  '__module__' : 'serv.iandun_pb2'
  # @@protoc_insertion_point(class_scope:pyserver.PhySiologicalCycleCommonModelReply)
  })
_sym_db.RegisterMessage(PhySiologicalCycleCommonModelReply)

PhySiologicalCyclePersonalModelRequest = _reflection.GeneratedProtocolMessageType('PhySiologicalCyclePersonalModelRequest', (_message.Message,), {
  'DESCRIPTOR' : _PHYSIOLOGICALCYCLEPERSONALMODELREQUEST,
  '__module__' : 'serv.iandun_pb2'
  # @@protoc_insertion_point(class_scope:pyserver.PhySiologicalCyclePersonalModelRequest)
  })
_sym_db.RegisterMessage(PhySiologicalCyclePersonalModelRequest)

PhySiologicalCyclePersonalModelReply = _reflection.GeneratedProtocolMessageType('PhySiologicalCyclePersonalModelReply', (_message.Message,), {
  'DESCRIPTOR' : _PHYSIOLOGICALCYCLEPERSONALMODELREPLY,
  '__module__' : 'serv.iandun_pb2'
  # @@protoc_insertion_point(class_scope:pyserver.PhySiologicalCyclePersonalModelReply)
  })
_sym_db.RegisterMessage(PhySiologicalCyclePersonalModelReply)

GenderReply = _reflection.GeneratedProtocolMessageType('GenderReply', (_message.Message,), {
  'DESCRIPTOR' : _GENDERREPLY,
  '__module__' : 'serv.iandun_pb2'
  # @@protoc_insertion_point(class_scope:pyserver.GenderReply)
  })
_sym_db.RegisterMessage(GenderReply)

PhyReply = _reflection.GeneratedProtocolMessageType('PhyReply', (_message.Message,), {
  'DESCRIPTOR' : _PHYREPLY,
  '__module__' : 'serv.iandun_pb2'
  # @@protoc_insertion_point(class_scope:pyserver.PhyReply)
  })
_sym_db.RegisterMessage(PhyReply)

PhySiologicalCycleStageReply = _reflection.GeneratedProtocolMessageType('PhySiologicalCycleStageReply', (_message.Message,), {
  'DESCRIPTOR' : _PHYSIOLOGICALCYCLESTAGEREPLY,
  '__module__' : 'serv.iandun_pb2'
  # @@protoc_insertion_point(class_scope:pyserver.PhySiologicalCycleStageReply)
  })
_sym_db.RegisterMessage(PhySiologicalCycleStageReply)

QuickRequest = _reflection.GeneratedProtocolMessageType('QuickRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUICKREQUEST,
  '__module__' : 'serv.iandun_pb2'
  # @@protoc_insertion_point(class_scope:pyserver.QuickRequest)
  })
_sym_db.RegisterMessage(QuickRequest)

QuickReply = _reflection.GeneratedProtocolMessageType('QuickReply', (_message.Message,), {
  'DESCRIPTOR' : _QUICKREPLY,
  '__module__' : 'serv.iandun_pb2'
  # @@protoc_insertion_point(class_scope:pyserver.QuickReply)
  })
_sym_db.RegisterMessage(QuickReply)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='pyserver.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=677,
  serialized_end=1251,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenderResults',
    full_name='pyserver.Greeter.GenderResults',
    index=0,
    containing_service=None,
    input_type=_GENDERREQUEST,
    output_type=_GENDERREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PhyResults',
    full_name='pyserver.Greeter.PhyResults',
    index=1,
    containing_service=None,
    input_type=_PHYREQUEST,
    output_type=_PHYREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PhySiologicalCycleStage',
    full_name='pyserver.Greeter.PhySiologicalCycleStage',
    index=2,
    containing_service=None,
    input_type=_PHYSIOLOGICALCYCLESTAGEREQUEST,
    output_type=_PHYSIOLOGICALCYCLESTAGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='QuickResults',
    full_name='pyserver.Greeter.QuickResults',
    index=3,
    containing_service=None,
    input_type=_QUICKREQUEST,
    output_type=_QUICKREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PhySiologicalCyclePersonalModel',
    full_name='pyserver.Greeter.PhySiologicalCyclePersonalModel',
    index=4,
    containing_service=None,
    input_type=_PHYSIOLOGICALCYCLEPERSONALMODELREQUEST,
    output_type=_PHYSIOLOGICALCYCLEPERSONALMODELREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PhySiologicalCycleCommonModel',
    full_name='pyserver.Greeter.PhySiologicalCycleCommonModel',
    index=5,
    containing_service=None,
    input_type=_PHYSIOLOGICALCYCLECOMMONMODELREQUEST,
    output_type=_PHYSIOLOGICALCYCLECOMMONMODELREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
